import { SignInButton } from "@clerk/nextjs";
import { useUser } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import LandingPage from "~/components/LandingPage";
import { api } from "~/utils/api";
import { GradientButton } from "~/components/GradientButton";
import Navbar from "~/components/Navbar";
import { Spinner } from "~/components/Spinner";
import Links from "./links";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useUser();
  if (!isLoaded) return <Spinner />;
  return (
    <>
      <Head>
        <title>FreeShipping</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {isSignedIn ? (
          <>
            <Links />

          </>
        ) : (
          <>
            <Navbar />
            <LandingPage />

          </>
        )}
      </main>
    </>
  );
};

export default Home;
